# Listing of sample groupings and cell type groupings
# to simplify parallelized processing in Snakemake workflows.
# TODO: use alternative mechanisms like Snakemake Checkpoints to make this more dynamic,
# getting the info directly from adata.uns where the metadata already exists.

cell_types:
  subclass_l1:
  - Ad
  - ATL
  - CNT
  - DCT
  - DTL
  - EC
  - FIB
  - IC
  - Lymphoid
  - Myeloid
  - NEU
  - PapE
  - PC
  - PEC
  - POD
  - PT
  - TAL
  - VSM/P
  subclass_l2:
  - aCNT
  - Ad
  - aDCT
  - aDTL
  - aEC-GC
  - angEC-PTC
  - aPT
  - aTAL
  - ATL
  - B
  - C-IC-A
  - C-PC
  - C-TAL
  - C/M-TAL
  - CNT
  - cycEC
  - cycMAC
  - cycPT
  - cycT
  - cycTAL
  - dATL
  - DC
  - dC-IC-A
  - dC-TAL
  - dCNT
  - DCT
  - dDCT
  - dDTL
  - dEC-AVR
  - dEC-GC
  - dEC-PTC
  - dFIB
  - dIMCD
  - dM-FIB
  - dM-IC-A
  - dM-PC
  - dM-TAL
  - dPOD
  - dPT
  - DTL1
  - DTL2
  - DTL3
  - dVSMC
  - EC-AA
  - EC-AVR
  - EC-DVR
  - EC-EA
  - EC-GC
  - EC-LYM
  - EC-PCV
  - EC-PTC
  - EC-V
  - ERY
  - FIB
  - frPT
  - frTAL
  - IC-B
  - IMCD
  - infEC-AVR
  - infEC-PTC
  - infFIB
  - M-FIB
  - M-IC-A
  - M-PC
  - M-TAL
  - MAST
  - MC
  - MD
  - moMAC
  - moMAC-INF
  - MON
  - MYOF
  - N
  - NK
  - PapE
  - PEC
  - PL
  - POD
  - PT-S1
  - PT-S2
  - PT-S3
  - pvFIB
  - REN
  - resMAC
  - SC/NEU
  - T
  - tPC-IC
  - VSMC
  - VSMC/P
  subclass_l3:
  - aCNT
  - Ad
  - aDCT
  - aDTL2
  - aEC-GC
  - angEC-PTC
  - aPT-S1/S2
  - aPT-S3
  - aPT1
  - aPT2
  - aTAL1
  - aTAL2
  - ATL
  - B
  - C-EC-PTC
  - C-FIB
  - C-FIB-OSMRhi
  - C-FIB-OSMRlo
  - C-FIB-PATH
  - C-MYOF
  - C-TAL-A
  - C-TAL-B
  - C/M-FIB
  - C/M-TAL-A
  - C/M-TAL-B
  - CCD-IC-A
  - CCD-PC
  - CD8+ TEM/TEMRA
  - CD8+ TEM/TRM
  - cDC1
  - cDC2
  - CNT
  - CNT-PC
  - cycEC
  - cycMAC
  - cycPT
  - cycT
  - cycTAL
  - dATL
  - dC-TAL
  - dCCD-IC-A
  - dCNT
  - dCNT-PC
  - DCT1
  - DCT2
  - dDCT
  - dDTL
  - dEC-AVR
  - dEC-GC
  - dEC-PTC
  - dFIB
  - dIM-FIB
  - dIMCD
  - dM-TAL
  - dOM-FIB
  - dOMCD-IC-A
  - dOMCD-PC
  - dPOD
  - dPT
  - dPT-S1
  - dPT-S2
  - dPT-S3
  - DTL1
  - DTL2
  - DTL3
  - dVSMC
  - EC-AA
  - EC-AVR
  - EC-DVR
  - EC-EA
  - EC-GC
  - EC-GC-FILIP1+
  - EC-LYM
  - EC-PCV
  - EC-V
  - ERY
  - frDCT
  - frPT-S1/S2
  - frPT-S3
  - frTAL
  - iaEC-AVR
  - iaEC-PTC
  - IC-B
  - ILC3
  - IM-FIB
  - IM-pvMYOF
  - IMCD
  - infEC-PTC
  - M-EC-PTC
  - M-TAL
  - M-VSMC/P
  - MAIT
  - MAST
  - MC
  - MD
  - mDC
  - moFAM
  - moMAC-C3+
  - moMAC-CXCL10+
  - moMAC-HBEGF+
  - MON
  - N
  - "Na\xEFve Th"
  - ncMON
  - NK
  - OM-FIB
  - OMCD-IC-A
  - OMCD-PC
  - PapE
  - pDC
  - PEC
  - PL
  - POD
  - PT-S1
  - PT-S2
  - PT-S3
  - pvFIB
  - pvFIB-PI16+
  - pvFIB-RSPO3+
  - pvMYOF
  - REN
  - resMAC-HLAIIhi
  - resMAC-LYVE1+
  - SC/NEU
  - T-REG
  - tOMCD-PC-IC
  - VSMC
  - VSMC/P
sample_group_pairs:
- colname: EnrollmentCategory
  lhs: Healthy Reference
  rhs: AKI
- colname: EnrollmentCategory
  lhs: AKI
  rhs: CKD
- colname: EnrollmentCategory
  lhs: CKD
  rhs: Healthy Reference
- colname: AdjudicatedCategory
  lhs: Diabetic Kidney Disease
  rhs: Healthy Reference
- colname: AdjudicatedCategory
  lhs: Acute Tubular Injury
  rhs: Healthy Reference
- colname: AdjudicatedCategory
  lhs: Acute Interstitial Nephritis
  rhs: Healthy Reference
- colname: AdjudicatedCategory
  lhs: Diabetic Kidney Disease
  rhs: Hypertensive Kidney Disease
- colname: AdjudicatedCategory
  lhs: Acute Interstitial Nephritis
  rhs: Acute Tubular Injury